# This file contains the default configuration for the Terem Core.
# Used for debug and linting purposes, all variables are prefilled.


# common
module_id: teremcore


# core commons
pipeline_width:  4


# verification
assertions: true
