# This file contains the default configuration for the Terem Core.
# Used for debug and linting purposes, all variables are prefilled.


# common
module_id: teremcore


# Core commons
pipeline_width:  4

# BP (branch predictor)
bp_pc_hash_bits: 8



# verification
assertions: true
